#!/usr/bin/env sh
alias cleawr="echo rawr"
alias cd="cd -P"
alias sniff="phpcs --standard='PSR12'"
alias fix="phpcbf --standard='PSR12'"
alias html="links -dump"
alias gs="git status ."
alias gp="git pull --ff-only"
alias gc="git checkout"
alias gb="git checkout -b"
alias gm="git merge --no-ff"
alias td="trolldev"
alias ch="chromium"
alias available="lux -l 0 -g 255 color"
alias dnd="lux -l 0 -r 255 color"
alias dcp="docker compose"

alias git-remove-untracked='git fetch --prune && git branch -r | awk "{print \$1}" | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk "{print \$1}" | xargs git branch -D'

release_branch() {
    git checkout -b release/$(date +%Y).w$(date +%V).r$1
}

reinit() {
    for gitdir in $(find . -maxdepth 2 -name .git | awk -F"." '{ print "." $2 }')
    do
        pushd $gitdir
        git init
        popd
    done
}

alias ec2list="aws ec2 describe-instances --query \"Reservations[*].Instances[*].{Instance:InstanceId,Name:Tags[?Key=='Name']|[0].Value}\" --output table"

alias drm="docker run --rm -it"
alias vim=nvim
