# tmux-powerline configuration.
export TMUX_POWERLINE_PATCHED_FONT_IN_USE="true"
export TMUX_POWERLINE_THEME="dracula"
export TMUX_POWERLINE_DIR_USER_THEMES="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-powerline/themes"
export TMUX_POWERLINE_DIR_USER_SEGMENTS="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-powerline/segments"
export TMUX_POWERLINE_STATUS_INTERVAL="5"
export TMUX_POWERLINE_STATUS_JUSTIFICATION="left"
export TMUX_POWERLINE_STATUS_LEFT_LENGTH="60"
export TMUX_POWERLINE_STATUS_RIGHT_LENGTH="180"
export TMUX_POWERLINE_WINDOW_STATUS_SEPARATOR=""

export TMUX_POWERLINE_SEG_WEATHER_UNIT="c"
export TMUX_POWERLINE_SEG_WEATHER_ICON_STYLE="nerdfonts"
