name: Build and test dotfiles

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: "Build and test"
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Setup docker buildkit
        uses: docker/setup-buildx-action@v4
      - name: Build
        uses: docker/build-push-action@v7
        with:
          push: false
          tags: test
          load: true
          context: .
          target: build
      - name: Test
        run: |
          docker run --rm -t test
